### ISSUE TITLE
NoMethodError occurs when unparseable code block is found

### ISSUE THREAD

**Issue by markburns** [markburns/to_factory#9]
Investigate:

```
NoMethodError: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.<=>
        from /home/markburns/code/to_factory/lib/to_factory/collation.rb:20:in `sort_by'
        from /home/markburns/code/to_factory/lib/to_factory/collation.rb:20:in `organize'
        from /home/markburns/.rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/activesupport-2.0.2/lib/active_support/inflector.rb:254:in `inject'
        from /home/markburns/code/to_factory/lib/to_factory/collation.rb:19:in `each'
        from /home/markburns/code/to_factory/lib/to_factory/collation.rb:19:in `inject'
        from /home/markburns/code/to_factory/lib/to_factory/collation.rb:19:in `organize'
        from /home/markburns/code/to_factory/lib/to_factory/collation.rb:6:in `organize'
        from /home/markburns/code/to_factory/lib/to_factory/file_sync.rb:16:in `all_representations'
        from /home/markburns/code/to_factory/lib/to_factory/file_sync.rb:12:in `perform'
        from /home/markburns/code/to_factory/lib/to_factory.rb:69:in `ToFactory'
```

**Comment by markburns** [comment]
I believe this is already handled
